/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_sl_testjniapp_jniTestOne_JniMethod */

#ifndef _Included_com_example_sl_testjniapp_jniTestOne_JniMethod
#define _Included_com_example_sl_testjniapp_jniTestOne_JniMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_sl_testjniapp_jniTestOne_JniMethod
 * Method:    getNativeString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_sl_testjniapp_jniTestOne_JniMethod_getNativeString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_sl_testjniapp_jniTestOne_JniMethod
 * Method:    getNativeNextString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_sl_testjniapp_jniTestOne_JniMethod_getNativeNextString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_sl_testjniapp_jniTestOne_JniMethod
 * Method:    getNativeNextInt
 * Signature: (ILjava/lang/String;ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_sl_testjniapp_jniTestOne_JniMethod_getNativeNextInt
  (JNIEnv *, jclass, jint, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
