/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_sl_testjniapp_jniTestOne_JniMethodC */

#ifndef _Included_com_example_sl_testjniapp_jniTestOne_JniMethodC
#define _Included_com_example_sl_testjniapp_jniTestOne_JniMethodC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_sl_testjniapp_jniTestOne_JniMethodC
 * Method:    getNativeCString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_sl_testjniapp_jniTestOne_JniMethodC_getNativeCString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_sl_testjniapp_jniTestOne_JniMethodC
 * Method:    getNativeCNextString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_sl_testjniapp_jniTestOne_JniMethodC_getNativeCNextString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_sl_testjniapp_jniTestOne_JniMethodC
 * Method:    getNativeCNextInt
 * Signature: (ILjava/lang/String;ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_sl_testjniapp_jniTestOne_JniMethodC_getNativeCNextInt
  (JNIEnv *, jclass, jint, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
